db.users.insertOne({
    userName: 'pako',
    Description: 'text...',
    initialWeek: [
        {
            day: 'monday',
            morning: ['Carrerita'],
            lunch: ['1APU', 'Dominadas set de 8x4 descanso 25"'],
            evening: [],
            night: [],
        },
        {
            day: 'tuesday',
            morning: [''],
            lunch: ['3x5 pike push ups', '2x 1APU'],
            evening: ['Anillas smartProgres'],
            night: [
                '4x30 cadena posterior',
                '4x30 pancake',
                '4x30 middle-split',
            ],
        },
        {
            day: 'wednesday',
            morning: ['Carrerita'],
            lunch: ['1APU', 'Dominadas set de 8x4 descanso 25"'],
            evening: [],
            night: [],
        },
        {
            day: 'thursday',
            morning: [''],
            lunch: ['3x5 pike push ups', '2x 1APU'],
            evening: [],
            night: [],
        },
        {
            day: 'friday',
            morning: [''],
            lunch: [],
            evening: [
                'Pinos (corto)',
                '3x 1APU',
                '5 pistol squad',
                '5 tiradas de front',
                'nordic curl 3x6',
                'tiradas de plancha',
                'Gemelos 3x10 44 kgs',
            ],
            night: [''],
        },
        {
            day: 'saturday',
            morning: [''],
            lunch: [''],
            evening: ['Descanso'],
            night: [],
        },
        {
            day: 'sunday',
            morning: [''],
            lunch: [''],
            evening: ['Descanso'],
            night: [],
        },
    ],
    purposeTraining: [
        {
            day: 'monday',
            morning: ['Carrerita'],
            lunch: ['1APU', 'Dominadas set de 8x4 descanso 25"'],
            evening: [],
            night: [],
        },
        {
            day: 'tuesday',
            morning: [''],
            lunch: ['3x5 pike push ups', '2x 1APU'],
            evening: ['Anillas smartProgres'],
            night: [],
        },
        {
            day: 'wednesday',
            morning: ['Carrerita'],
            lunch: ['1APU', 'Dominadas set de 8x4 descanso 25"'],
            evening: [
                {
                    Pierna: [],
                },
            ],
            night: [],
        },
        {
            day: 'thursday',
            morning: [''],
            lunch: ['3x5 pike push ups', '2x 1APU'],
            evening: [
                'Pinos (largo)',
                '5x 1APU',
                '10x flex a pino',
                '5 pistol squad',
                '3x12 fondos',
                '3x20 flexiones',
            ],
            night: [],
        },
        {
            day: 'friday',
            morning: [''],
            lunch: ['1APU', 'Dominadas set de 8x4 descanso 25"'],
            evening: [],
            night: [''],
        },
        {
            day: 'saturday',
            morning: [''],
            lunch: [''],
            evening: ['Descanso'],
            night: [],
        },
        {
            day: 'sunday',
            morning: [''],
            lunch: [''],
            evening: ['Descanso'],
            night: [],
        },
    ],
});
