db.users.insertOne({
	userName: "mike",
	Description: "text...",
	initialWeek: [
		{
			day: "monday",
			morning: ["Carrerita"],
			lunch: ["1APU", 'Dominadas set de 8x4 descanso 25"'],
			evening: [
				"5x pike pushups",
				"10 intentos de flexión a pino",
				"2x5 pike push ups",
				"5 pistol squads",
				"Gemelos 3x10 44kgs",
			],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
		{
			day: "tuesday",
			morning: [""],
			lunch: ["3x5 pike push ups", "2x 1APU"],
			evening: ["Anillas smartProgres"],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
		{
			day: "wednesday",
			morning: ["Carrerita"],
			lunch: ["1APU", 'Dominadas set de 8x4 descanso 25"'],
			evening: [
				{
					Pierna: [
						"3x45'' isometrico sentadillas",
						"5 pistol squad",
						"3x6 nordic curl",
						"4x8 sentadillas 44kgs",
						"Peso muerto 4x10 44kgs",
						"Gemelos 3x10 44kgs",
					],
				},
			],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
		{
			day: "thursday",
			morning: [""],
			lunch: ["3x5 pike push ups", "2x 1APU"],
			evening: [
				"Pinos (largo)",
				"5x 1APU",
				"10x flex a pino",
				"5 pistol squad",
				"3x12 fondos",
				"3x20 flexiones",
			],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
		{
			day: "friday",
			morning: [""],
			lunch: ["1APU", 'Dominadas set de 8x4 descanso 25"'],
			evening: [
				"Pinos (corto)",
				"3x 1APU",
				"5 pistol squad",
				"5 tiradas de front",
				"nordic curl 3x6",
				"tiradas de plancha",
				"Gemelos 3x10 44 kgs",
			],
			night: [""],
		},
		{
			day: "saturday",
			morning: [""],
			lunch: [""],
			evening: ["Descanso"],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
		{
			day: "sunday",
			morning: [""],
			lunch: [""],
			evening: ["Descanso"],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
	],
	purposeTraining: [
		{
			day: "monday",
			morning: ["Carrerita"],
			lunch: ["1APU", 'Dominadas set de 8x4 descanso 25"'],
			evening: [
				"5x pike pushups",
				"10 intentos de flexión a pino",
				"2x5 pike push ups",
				"5 pistol squads",
				"Gemelos 3x10 44kgs",
			],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
		{
			day: "tuesday",
			morning: [""],
			lunch: ["3x5 pike push ups", "2x 1APU"],
			evening: ["Anillas smartProgres"],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
		{
			day: "wednesday",
			morning: ["Carrerita"],
			lunch: ["1APU", 'Dominadas set de 8x4 descanso 25"'],
			evening: [
				{
					Pierna: [
						"3x45'' isometrico sentadillas",
						"5 pistol squad",
						"3x6 nordic curl",
						"4x8 sentadillas 44kgs",
						"Peso muerto 4x10 44kgs",
						"Gemelos 3x10 44kgs",
					],
				},
			],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
		{
			day: "thursday",
			morning: [""],
			lunch: ["3x5 pike push ups", "2x 1APU"],
			evening: [
				"Pinos (largo)",
				"5x 1APU",
				"10x flex a pino",
				"5 pistol squad",
				"3x12 fondos",
				"3x20 flexiones",
			],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
		{
			day: "friday",
			morning: [""],
			lunch: ["1APU", 'Dominadas set de 8x4 descanso 25"'],
			evening: [
				"Pinos (corto)",
				"3x 1APU",
				"5 pistol squad",
				"5 tiradas de front",
				"nordic curl 3x6",
				"tiradas de plancha",
				"Gemelos 3x10 44 kgs",
			],
			night: [""],
		},
		{
			day: "saturday",
			morning: [""],
			lunch: [""],
			evening: ["Descanso"],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
		{
			day: "sunday",
			morning: [""],
			lunch: [""],
			evening: ["Descanso"],
			night: [
				"4x30 cadena posterior",
				"4x30 pancake",
				"4x30 middle-split",
			],
		},
	],
});
